    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Set up JDK 16
            uses: actions/setup-java@v2
            with:
              java-version: '16'
              distribution: 'adopt'
          - uses: education/autograding@v1
